# ===================================================================
# Spring Boot configuration
# ===================================================================

spring:
  application:
    name: whotw-template
  profiles:
    active: dev
# ===================================================================
# Project specific properties
# ===================================================================
whotw:

# ===================================================================
# Application specific properties
# ===================================================================

application:

